# Bakin Documentation Scraper Configuration

# Base URL for Bakin C# Reference Documentation
base_url: "https://rpgbakin.com/csreference/doc/ja"
namespaces_url: "https://rpgbakin.com/csreference/doc/ja/namespaces.html"

# HTTP Client Settings
http:
  timeout: 30  # seconds
  max_retries: 3
  retry_delay: 1.0  # seconds between retries
  rate_limit_delay: 1.0  # seconds between requests

# Output Settings
output:
  json_dir: "output/json"
  markdown_dir: "output/markdown"
  include_timestamp: true
  backup_existing: true

# Scraping Settings
scraping:
  batch_size: 10  # number of classes to process in each batch
  save_progress: true
  resume_on_restart: true

# Logging Settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  console_output: true
  file_output: true
  log_file: "output/scraper.log"
  max_log_size: 10485760  # 10MB
  backup_count: 5