name: Claude Code Review

on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  claude-review:
    if: (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@claude')) || (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Claude Code Review
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          track_progress: true
          claude_args: "Bash(gh pr comment:*)"
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}
            
            このPRをレビューしてください。コードの品質、セキュリティ、ベストプラクティスの観点からフィードバックを提供し、
            改善点があれば具体的な提案をしてください。
            
            レビューが完了したら、必ずBashツールを使用して以下のコマンドでPRにコメントを投稿してください：
            gh pr comment ${{ github.event.pull_request.number || github.event.issue.number }} --body "レビュー結果をここに記載"
            
            レビュー結果は日本語で投稿してください。
            
